### ISSUE TITLE
The readme claims the Windows release includes all needed dependencies but the Visual Studio runtime is not included

### ISSUE THREAD

**Issue by pmaanen** [labstreaminglayer/App-LabRecorder#104]
> README.md:
> The Windows archives ship with all required dependencies.

I just tried to help a student install LabRecorder-1.16.4 on a Windows 11 machine, the LabRecorder did not start complaining about missing DLLs. Installing the newest Visual Studio Runtime solved the problem. Either include the Visual Studio runtime DLLs or make the user aware of the dependency.

**Comment by cboulay** [comment]
FIxed. Thanks.
