### ISSUE TITLE
Can't open Labrecorder on M1 Mac

### ISSUE THREAD

**Issue by Matthew910818** [labstreaminglayer/App-LabRecorder#109]
I tried to open Labrecorder on the computer but it kept popping out this error.
<img width="866" alt="截圖 2023-11-23 下午5 03 48" src="https://github.com/labstreaminglayer/App-LabRecorder/assets/107916838/77a841d9-dc78-43bb-9057-21201a011740">

**Comment by cboulay** [comment]
How did you install LabRecorder?

This is a problem with the Qt that comes from homebrew. See here: https://bugreports.qt.io/browse/QTBUG-100686

The solution is to build LabRecorder yourself.

**Comment by Matthew910818** [comment]
I followed the steps in this website (https://github.com/labstreaminglayer/App-LabRecorder/blob/master/BUILD.md), but after cmake the LabRecorder.app shows that the app is crushed or not complete.

**Comment by Matthew910818** [comment]
The problem is solved, thank you!
