### ISSUE TITLE
Create Release for LabRecorder

### ISSUE THREAD

**Issue by mgrivich** [labstreaminglayer/App-LabRecorder#14]
I believe the most recent version of LabRecorder on the ftp includes the clock offsets bug. We should make a new release, and post it to this repository. I could do it, but I know that LabRecorder is under active development at the moment so I hesitate to step on any toes.

**Comment by cboulay** [comment]
The release page now has working versions for MacOS (auto-deployed to release page whenever a commit with a tag is pushed). The Windows versions are also auto-deployed but they're missing the Qt dlls. #16 I'm trying to fix that.

**Comment by cboulay** [comment]
I built it manually and uploaded it.
https://github.com/labstreaminglayer/App-LabRecorder/releases/tag/timeout_fix_tag3
