### ISSUE TITLE
LabStreamingLayer transmission problem

### ISSUE THREAD

**Issue by qwe23123a** [labstreaminglayer/App-LabRecorder#17]
This is the steram problem of LabRecorder reading two computers. The main computer is the window 10 system, and the other computer is the window 7 system. I let window 10 and window 7 each send a stream. When I open LabRecorder in window10, there is only its own stream, and I open window7's LabRecorder with two streams. Then I press Update in the LabRecorder of window10 and two streams will appear.
But after I started recording and stopped, he would show no response, but there is still a .xdf file.
I use matlab to read the .xdf file and only have one stream of window10.
I am recording a video. Both computers are on the same domain and the firewall is down.
This is the video URL: https://youtu.be/kfY2FsC0U8Y

**Comment by agricolab** [comment]
Dear @qwe23123a , sounds like a network connectivity problem. So, would this wiki-entry help?
https://github.com/sccn/labstreaminglayer/wiki/NetworkConnectivity

**Comment by qwe23123a** [comment]
> Dear @qwe23123a , sounds like a network connectivity problem. So, would this wiki-entry help?
> https://github.com/sccn/labstreaminglayer/wiki/NetworkConnectivity

I tried to switch the public network to work or home network, there is a problem that window10 can't receive two streams.
I guess it may be caused by the following conditions
"when you have multiple (perhaps virtual) network adapters, and the primary network adapter is not the one that can communicate with other machines."
Because my window10 is the network route, and window7 is wifi, although they are all under the same domain, but the above situation may occur.

Thank you very much for your help.

**Comment by dmedine** [comment]
Windows 10 has a nasty habit of spawning these virtual network adapters. 
I really don't understand why it does this and I don't know of a solid, 
non-hacky way to deal with this. I have had some luck deleting or 
disabling the virtual adapters (doesn't always work!) and restarting the 
computer. A network switch will also make your life easier. You can also 
ask Windows to make an adapter the primary one, but this is also flaky 
when done in user space.
