### ISSUE TITLE
Running Lab Recorder CLI  from an external process records duplicate streams.

### ISSUE THREAD

**Issue by Gnarlywhale** [labstreaminglayer/App-LabRecorder#22]
I encountered this issue when starting LabRecorderCLI from an external C# program that I'm working on (similar to @agricolab's project). I am able to start LabRecorderCLI with the file name and target streams as a separate process, but the resulting file contains multiple copies of the same stream. 

To duplicate:
 - create a shortcut for LabRecorderCLI.exe
 - Right click the shortcut and select properties
 - Under the "Shortcut" tab, change the "Target" to include the arguments of multiple streams:
`"C:\Users\Deep Thought\source\repos\LabRemote\LabRemote\bin\Debug\LabRecorderCLI.exe" trialName.xdf 'name="Keyboard"' 'name="LabRemote"'`
![image](https://user-images.githubusercontent.com/3422267/71929237-6afaef00-3156-11ea-8103-8d3da163d949.png)

 - Run the shortcut:
![image](https://user-images.githubusercontent.com/3422267/71928830-8ca7a680-3155-11ea-9ccb-90e16879c7e1.png)

Note that there appears to be 4 streams while there should only be 2.

Frustratingly, this error doesn't occur when starting the program directly from command line:
![image](https://user-images.githubusercontent.com/3422267/71928978-de503100-3155-11ea-9721-214b70fe2c5c.png)

Any idea what's going on?

**Comment by cboulay** [comment]
The only difference I could imagine is that the arguments are parsed differently depending on whether you're using powershell or launching from a shortcut.

A short-term solution is to create a shortcut to a powershell script. Can you verify that works?

I don't know how to debug this. I know how to put a break mark and debug the process when launched from within Visual Studio. I'm not good enough with Visual Studio to know how to get it to monitor for any process named LabRecorderCLI then attach its debugger as soon as it's found. If I knew how to do that, I would debug the arguments that get passed into the program when it's run from a shortcut or from a powershell prompt to see what's different.

**Comment by Gnarlywhale** [comment]
You're intuition was correct and clued me in on a fix!

The key was noticing that running the shortcut launched Lab Recorder CLI using **Command Prompt** instead of **Powershell** (which is what I had used to build and test the initial call). It turns out C#'s `Process.Start()` method processes arguments the same as the Command Prompt, so I needed to change how I was launching Lab Recorder CLI:
`startInfo.Arguments = "_1.xdf  \"name=\"\"Keyboard\"\"\" \"name=\"\"LabRemote\"\"\" "`

Thanks for the insight 👍
