### ISSUE TITLE
Ubuntu release missing liblsl

### ISSUE THREAD

**Issue by JadinTredup** [labstreaminglayer/App-LabRecorder#23]
Hello, whenever I try to call LabRecorder from the command line (Ubuntu 18.04) I get the following error:
`LabRecorder: error while loading shared libraries: liblsl64.so.1.13.0: cannot open shared object file: No such file or directory`

**Comment by agricolab** [comment]
It seems you are running LabRecorder on Linux and missing the shared library (i.e. liblsl). Try installing liblsl first. You can find releases here https://github.com/sccn/liblsl/releases
