### ISSUE TITLE
Remote Control Socket feature unable to handle spaces in filename updates?

### ISSUE THREAD

**Issue by NIH-FAB** [labstreaminglayer/App-LabRecorder#32]
I'm trying to control LabRecorder via RCS with Matlab. I'm able to send commands to start/stop recording as well as change the filename fields, however the Study Root field fails to update when I send a path that includes space characters. Similarly, I haven't been able to remotely update the template field (using %b,%s,%p). It looks like these are issues with the regex patterns specified in mainwindow.cpp. Just wondering if this feature is intentional or if it could be easily modified.

**Comment by cboulay** [comment]
Closed with #33
