### ISSUE TITLE
LabRecorder-1.13.1-Linux64-bionic.deb depends from labrecorder-liblsl

### ISSUE THREAD

**Issue by acompagn** [labstreaminglayer/App-LabRecorder#45]
Hi,
I cannot install LabRecorder-1.13.1 from the deb package as it asks for the dependency labrecorder-liblsl which I cannot find. It is supposed to be the liblsl deb package available as a release in the liblsl repo? if so the name does not match and the dependency cannot be satisfied.

Moreover I noticed the deb package lsl-1.13.1-Linux-liblsl.deb among the debs in the latest release of LabRecorder however is seems to be empty.

Thanks,
Alberto

**Comment by tstenner** [comment]
I can reproduce this in parts. I'll investigate this in a few weeks when I've got some spare time.

**Comment by acompagn** [comment]
Thanks

**Comment by tstenner** [comment]
I think I've got this solved. In a nutshell: the build script set a lot of packaging options for each component, only for the build system to throw everything away when there's only a single component to be built *sigh*. In liblsl v1.14.0b5 this should be fixed. As soon as I've confirmed it, I'll close the issue.

**Comment by tstenner** [comment]
> In liblsl v1.14.0b5 this should be fixed. As soon as I've confirmed it, I'll close the issue.
