### ISSUE TITLE
Unmet dependency Ubuntu: Package 1 is not installed

### ISSUE THREAD

**Issue by mapaaa** [labstreaminglayer/App-LabRecorder#54]
Hello!
I get an error while installing LabRecorder-1.14.0-focal_amd64.deb on Ubuntu 20.04.2 LTS.
I first installed the liblsl 1.14.0 with no problem.
Then, when I try to install LabRecorder it gives a strange output:

dpkg: dependency problems prevent configuration of labrecorder:
 labrecorder depends on 1; however:
  Package 1 is not installed.

What is package 1?

**Comment by SveaMeyer13** [comment]
+ 1 with exactly the same issue 

Thank you :)

**Comment by tstenner** [comment]
I don't know what package 1 is and why it's in there, but in the current CI builds it's not there any more. I have rebuilt the package and uploaded it, now the dependencies are correct:

```
$ dpkg -I LabRecorder-1.14.0-focal_amd64.deb
[..]
Depends: libc6 (>= 2.14), libgcc-s1 (>= 3.0), liblsl (= 1.14.0-focal), libqt5core5a (>= 5.12.2), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.0.2), libstdc++6 (>= 9)
```

**Comment by mapaaa** [comment]
The package works now! Thanks!
