### ISSUE TITLE
MacOS 1.14 and 1.13 releases

### ISSUE THREAD

**Issue by arnodelorme** [labstreaminglayer/App-LabRecorder#55]
Do not work on Mojave. Neither version (tried all the OSx files). 1.12 works.

**Comment by arnodelorme** [comment]
<img width="420" alt="Screen Shot 2021-03-11 at 1 02 50 PM" src="https://user-images.githubusercontent.com/1872705/110867028-3018ad80-826a-11eb-9e80-808a0adc8c85.png">

**Comment by cboulay** [comment]
I don't have a Mac running 10.14 (Mojave). Please test this file: https://github.com/labstreaminglayer/App-LabRecorder/releases/download/v1.14.0/LabRecorder-1.14.0-OSX-10.14_amd64.tar.bz2

**Comment by arnodelorme** [comment]
That works.

**Comment by cboulay** [comment]
Fixed in d7a42809dca41450d1fb882719050115e74f14d5
I'm not making a specific release for this. Future releases will have this fix built-in. Until then, use the OSX-10.14 file on the 1.14.0 release.
