### ISSUE TITLE
GUI blurry on OSx

### ISSUE THREAD

**Issue by arnodelorme** [labstreaminglayer/App-LabRecorder#56]

**Comment by cboulay** [comment]
In your other issue you said that LabRecorder 1.13 and 1.14 don't work for you on MacOS Mojave. Are you experiencing this on a different version of MacOS? Or is this with LabRecorder 1.12?

Here's what it looks like for me on MacOS 11.2 using the file that I linked in the other issue.
<img width="909" alt="Screen Shot 2021-03-12 at 2 13 36 AM" src="https://user-images.githubusercontent.com/303797/110905574-aa801680-82d8-11eb-8fee-647e331a2067.png">

**Comment by arnodelorme** [comment]
The background for me is light and it is still blurry. It is usable though.

**Comment by cboulay** [comment]
The background colour is inherited from the OS settings. I happen to be running in Dark Mode.

I recreated the package targeting 10.14 and added an extra flag into the Info.plist file that's supposed to fix the problem. Please test it and report back. (On my system they all look sharp so I can't test effectively)

https://github.com/labstreaminglayer/App-LabRecorder/releases/download/v1.14.0/LabRecorder-1.14.0-OSX-10.14_amd64.tar.bz2

**Comment by arnodelorme** [comment]
Yes, this version works and no more blur. Tx

**Comment by cboulay** [comment]
Fixed in d7a42809dca41450d1fb882719050115e74f14d5
Future releases will have it built in.
