### ISSUE TITLE
Building 1.14.1 on Windows 10

### ISSUE THREAD

**Issue by StylianosBakas** [labstreaminglayer/App-LabRecorder#62]
In an upcoming experiment, I require the use of the update stream feature via RCS (introduced in 1.14.1). However, I am having issues with building from source. Is there a schedule for an upcoming release that would alleviate the need to build from source? If not, my current setup is using cmake (3.20.1) on Windows 10 to build the solution from source, using Qt5 (5.15.2) and LSL (1.14.0) and selecting Visual studio 2019 as the generator using the default native compiler . The configuration and generation of the solution works fine, but when I try to build the project in Visual Studio 2019 (16.9.4) the LabRecorder component can't be built. I get 763 errors, all of them being either LNK1120, LNK2001 and LNK2019.  I think it can't properly link Qt since all of the errors are regarding Qt.

**Comment by cboulay** [comment]
One thing I encountered recently while helping a different user is that their Qt Installer defaulted to installing the MinGW binaries, not the MSVC binaries. @StylianosBakas - please make sure you have the correct Qt binaries installed. Then the argument you pass to CMake would be `-DQt5_DIR=C:\Qt\5.15.2\msvc2019_64\lib\cmake\Qt5` (assuming default Qt install directory and 64-bit build).

**Comment by StylianosBakas** [comment]
> One thing I encountered recently while helping a different user is that their Qt Installer defaulted to installing the MinGW binaries, not the MSVC binaries. @StylianosBakas - please make sure you have the correct Qt binaries installed. Then the argument you pass to CMake would be `-DQt5_DIR=C:\Qt\5.15.2\msvc2019_64\lib\cmake\Qt5` (assuming default Qt install directory and 64-bit build).

You are absolutely right, I didn't even notice it. After installing the correct Qt binaries, it built just fine. Thank you very much for your help!
