### ISSUE TITLE
MacOS to Window streaming Issue.

### ISSUE THREAD

**Issue by iPsych** [labstreaminglayer/App-LabRecorder#67]
When Stream EEG data via LSL in MacOS (High Sierra), the same Macbook Pro can record the stream properly with LabRecorder.
However, the Windows machine in the same network can find lsl_inlet, and connect, but cannot pull samples.
Same issue happened both in Matlab and Compiled Lab Recorder.

Is there anything I should consider?

**Comment by cboulay** [comment]
Hi this isn't really a LabRecorder issue. Can you please comment on an issue in the main liblsl repo? It will get more eyes there.
https://github.com/sccn/liblsl/issues/29 might be a good one.
