### ISSUE TITLE
I cannot get output file. a problem on windows 11 ?

### ISSUE THREAD

**Issue by atusiniida** [labstreaminglayer/App-LabRecorder#75]
Dear colleagues, 

Following a tutorial. I tried to get data from AudioCapture on my windows 11 PC.
https://github.com/sccn/labstreaminglayer/wiki/Tutorial-1.-Getting-started-with-LSL-single-stream
However, I failed to get an output .xdf file.
I do not get any error or warning messages. 
but the value indicating the size of the output file remains zero (a below figure)  and I do not find any files in the specified path.

<img width="850" alt="スクリーンショット 2021-12-15 102551" src="https://user-images.githubusercontent.com/4198384/146107267-d7800c62-547d-4f82-9b5f-070307d13bb8.png">

I have confirmed that this problem occurs in the following version.
LabRecorder-1.13.1-win64
LabRecorder-1.14.2-Win_amd64
LabRecorder-1.14.2-Win_i386

the same problem occurs when I tried data from BlueMuse on my windows 11 PC.
https://github.com/kowalej/BlueMuse
I successfully get the output file from AudioCapture on my MAC PC.

therefore, I suspect that this problem is specific to my windows 11 PC.

It is very helpful if you give any advice about this problem.
Thank you in advance.

**Comment by cboulay** [comment]
Can you verify that data are coming through using another LSL application? For example, in a simple pylsl instance, or one of the viewers here: https://labstreaminglayer.readthedocs.io/info/viewers.html

**Comment by atusiniida** [comment]
Thank you for your response.
I tried a combination of BlueMuse and muse-lsl ( https://github.com/alexandrebarachant/muse-lsl).
It worked with no problem.

**Comment by agricolab** [comment]
You have a very weird file name, actually it seems invalid for the Win11 filesystem. My guess is that either LabRecorder or Win11 can't handle that. Try changing the filename?
![image](https://user-images.githubusercontent.com/20556511/146141533-c4275b16-f8a4-4955-be04-ae4fce95fb1e.png)

**Comment by agricolab** [comment]
If that's the default filename for LabRecorder on Win11, there might be a decoding issue in the code.

**Comment by atusiniida** [comment]
Thanks!   I have Japanese characters in the file name.  As you point out, Mojibake is the cause of the problem. I got the data in a  path without Japanese characters.
