### ISSUE TITLE
Package "1" dependency

### ISSUE THREAD

**Issue by nvbln** [labstreaminglayer/App-LabRecorder#79]
Currently if I try to install App-LabRecorder (version 1.14.2, but the latest version has the same problem) on Ubuntu 21.10, I get the following error:
`The following packages have unmet dependencies:
 labrecorder : Depends: 1 but it is not installable`

I do not know what the purpose was of adding '1' to the dependency list, but it does not seem to refer to an actual package (as far as I am aware) and LabRecorder seems to run fine without the dependency so far.

Fixing this issue should be as simple as removing '1' from the control file for the Debian package (for users of LabRecorder, downloading the `.deb` file and executing the commands listed here: https://serverfault.com/a/383958 should do the trick until this bug has been fixed).

**Comment by agricolab** [comment]
Can replicate 

<pre><font color="#4E9A06">└─ #1 </font> sudo dpkg -i LabRecorder-1.16.0-bionic_amd64.deb 
Selecting previously unselected package labrecorder.
(Reading database ... 628452 files and directories currently installed.)
Preparing to unpack LabRecorder-1.16.0-bionic_amd64.deb ...
Unpacking labrecorder (1.16.0-bionic) ...
<b>dpkg:</b> dependency problems prevent configuration of labrecorder:
 labrecorder depends on 1; however:
  Package 1 is not installed.

<b>dpkg:</b> error processing package labrecorder (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 labrecorder</pre>

**Comment by agricolab** [comment]
Likely originating from the github actions setup:
[                -DCPACK_DEBIAN_PACKAGE_DEPENDS=1 \](https://github.com/labstreaminglayer/App-LabRecorder/blob/master/.github/workflows/cppcmake.yml#L87-L88)

**Comment by cboulay** [comment]
@agricolab , I think you're right. Do you mind putting together a PR?
