### ISSUE TITLE
LabRecorder is not automatically put in the PATH on Linux

### ISSUE THREAD

**Issue by nvbln** [labstreaminglayer/App-LabRecorder#80]
I am not familiar with building Debian packages myself, so I am not sure what the best way is to proceed, but after installing the LabRecorder package on Linux (Ubuntu 21.10) it was not listed in my path, nor did I know its installation location. Either putting the executable in the path or clarifying its installation location would definitely help from a user perspective. :)

**Comment by cboulay** [comment]
Fixed in a528dd1a97f46bd772fdbbc1013d27a0bcdd8a07
