### ISSUE TITLE
Add the ability to build CLI only

### ISSUE THREAD

**Issue by Roedy13** [labstreaminglayer/App-LabRecorder#85]
I want to use LabRecorderCLI in an embedded, containerized application.  There is no reason to install QT libraries into the container when they will never be used.  It would be extremely helpful to have a cmake option to only compile `LabRecoderCLI`

I've written a CMakeList.txt file to enable this, and I'd be happy to push it up, but it seems I don't have permission to create a new branch.

**Comment by agricolab** [comment]
Thanks! That sounds like a very interesting option. What would work is that you fork the repo, and then create your own branch for a PR.
