### ISSUE TITLE
Support for 22.04 LTS

### ISSUE THREAD

**Issue by mscheltienne** [labstreaminglayer/App-LabRecorder#90]
I just gave a shot to installing the 20.04 `.deb` on a 22.04 LTS, and it failed with code 100.
Could you build and release the `.deb` compatible for the latest ubuntu version?

**Comment by cboulay** [comment]
[LabRecorder-1.16.2-jammy_amd64.zip](https://github.com/labstreaminglayer/App-LabRecorder/files
[liblsl-1.16.0-jammy_amd64.zip](https://github.com/labstreaminglayer/App-LabRecorder/files/10304074/liblsl-1.16.0-jammy_amd64.zip)
/10304067/LabRecorder-1.16.2-jammy_amd64.zip)

Unzip these somewhere. cd into that folder, then run...

* `sudo apt install qt6-base-dev freeglut3-dev`
* `sudo dpkg -i liblsl-1.16.0-jammy_amd64.deb`
* `sudo dpkg -i LabRecorder-1.16.2-jammy_amd64.deb`
* `/usr/LabRecorder/LabRecorder`

(I should probably figure out how to put that in `usr/bin/`.)

**Comment by cboulay** [comment]
The `/usr/LabRecorder` vs `/usr/bin/LabRecorder` issue still isn't resolved, but I cleaned up the build system and made a new release that includes Jammy targets: https://github.com/labstreaminglayer/App-LabRecorder/releases/tag/v1.16.3

So this should be closed.

**Comment by mscheltienne** [comment]
Thank you, I will be able to test those in the first week of January.

**Comment by mscheltienne** [comment]
Looks like there is a version pin on `liblsl` somewhere. 
When I setup a new PC, I usually use the latest versions, in this case: `liblsl: 1.16.1`. The LabRecorder install then fails with:

```
Depends: liblsl (= 1.16.0-jammy) but 1.16.1-jammy is to be installed
```
