### ISSUE TITLE
Data conversion

### ISSUE THREAD

**Issue by TomasSand** [labstreaminglayer/App-LabRecorder#98]
Good morning, i'have two time stamps from two streaming flow. The First timestamp(marker position) is 1543312.81554 relative to this date: 1970-01-18 21:41:52. Second timestamp(eeg flow) is 1687166433.77987 relative to this date: 2023-06-19 11:20:33. It's possible align this two timestamp to obtain the marker position?
I see this data using pyxdf and pyxdf.load_xdf(filename) method to load xdf file. I have used labrecording to recording data.
thanks in advance.

**Comment by cboulay** [comment]
Hi @TomasSand , apologies for the slow reply.

What are the stream origins? Some LSL integrations incorrectly set the timestamp at the source which could cause your problem.

**Comment by cboulay** [comment]
Hi @TomasSand , we really can't help you unless you tell us what the stream origins are. Closing as non-responsive.
